services:
  - type: web
    name: faradayx-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir backend server:app"
    healthCheckPath: "/api/hardware"
